import type { Article } from '@/types/content';

export const frontendBasePathArticle: Article = {
  id: 'frontend-base-path-vite-nextjs',
  slug: 'frontend-base-path-vite-nextjs',
  category: 'Frontend',
  title: 'Frontend Base Paths: Deploying Vite and Next.js Apps Under a URL Prefix',
  summary:
    'A beginner-first explanation of what a frontend base path actually means, why applications break when deployed under a sub-path, and how Vite, React Router, and Next.js handle the concept with base, basename, and basePath.',
  topics: ['React', 'Vite', 'Next.js', 'Routing', 'Deployment'],
  difficulty: 'intermediate',
  blocks: [
    {
      type: 'paragraph',
      text: 'Most frontend applications are developed as if they own an entire domain. You run the application at `http://localhost:5173/`, deploy it to `https://example.com/`, and everything seems straightforward. Then someone says, "We need this application under `/admin/` because the main website already exists." Suddenly JavaScript files start returning 404s, routes behave strangely, and a configuration option called `base`, `basePath`, or `basename appears`. This article starts with the underlying web concept instead of jumping straight into framework configuration: what does it actually mean for an application to live under a URL prefix, and what does each layer of the frontend need to know about it?'
    },
    {
      type: 'heading',
      id: 'what-is-a-base-path',
      level: 2,
      text: 'What is a base path?'
    },
    {
      type: 'paragraph',
      text: 'A base path is the URL path under which your frontend application is publicly available. If your application is hosted at `https://example.com/`, its base path is effectively `/`. If the same application is hosted at `https://example.com/admin/`, its base path is `/admin/`. The important idea is that the application no longer owns the root of the domain. It has been mounted inside a particular part of the URL space.'
    },
    {
      type: 'table',
      columns: ['Deployment URL', 'Base path', 'Meaning'],
      rows: [
        ['https://example.com/', '/', 'The application is mounted at the domain root'],
        ['https://example.com/admin/', '/admin/', 'The application is mounted under /admin/'],
        ['https://example.com/dashboard/', '/dashboard/', 'The application is mounted under /dashboard/'],
        ['https://example.com/company/tools/', '/company/tools/', 'The application is mounted under a deeper path']
      ]
    },
    {
      type: 'paragraph',
      text: 'This sounds almost embarrassingly simple, but the distinction matters because a frontend application does not consist of one file. The browser may need to download JavaScript chunks, CSS, fonts, images, and other resources, and it may navigate between many application routes. Once the application lives under `/admin/`, all of those URL decisions need to agree about where the application begins.'
    },
    {
      type: 'heading',
      id: 'root-vs-subpath-deployment',
      level: 2,
      text: 'Root deployment vs sub-path deployment'
    },
    {
      type: 'paragraph',
      text: 'Consider a normal root deployment. The browser visits `https://example.com/`, and the application effectively owns `/`. A generated JavaScript asset such as `/assets/app.js` therefore points to `https://example.com/assets/app.js`, which is exactly where the browser expects to find it.'
    },
    {
      type: 'paragraph',
      text: 'Now move the application to `https://example.com/admin/`. The application owns `/admin/`, not `/`. An asset that belongs to this application may now need to be requested from `/admin/assets/app.js`. If the application continues generating `/assets/app.js`, the browser will request the file from the root of the domain instead of from the application directory.'
    },
    {
      type: 'code',
      language: 'markdown',
      code: `Root deployment

https://example.com/
├── assets/
│   └── app.js
└── ...


Sub-path deployment

https://example.com/admin/
├── assets/
│   └── app.js
└── ...`
    },
    {
      type: 'callout',
      variant: 'note',
      title: 'The browser only sees URLs',
      text: 'Your source project may have a `src/` directory, a `components/` directory, and hundreds of npm packages, but the browser does not know or care about that structure. It receives URLs and makes HTTP requests. A base path is ultimately about making the URLs generated by your application match the place where the application is actually being served.'
    },
    {
      type: 'heading',
      id: 'why-would-you-use-a-subpath',
      level: 2,
      text: 'Why would an application be deployed under a sub-path?'
    },
    {
      type: 'paragraph',
      text: 'The most common reason is that one domain hosts multiple applications. A company might have an existing website at `https://company.com/`, an administration application at `https://company.com/admin/`, an analytics application at `https://company.com/analytics/`, and a customer portal at `https://company.com/portal/`. Each application has its own codebase and deployment, but they share the same public domain.'
    },
    {
      type: 'paragraph',
      text: 'Another common case is hosting platforms that give a project its own path. GitHub Pages, for example, can serve a project from a repository path such as `https://username.github.io/my-project/`. The application is therefore not mounted at `/`; it is mounted at `/my-project/`.'
    },
    {
      type: 'paragraph',
      text: 'Sub-path deployment can also appear when an organization gradually replaces an existing application. The old application might continue handling `/`, while a newly built React or Next.js application is introduced at `/dashboard/` without taking over the entire domain.'
    },
    {
      type: 'heading',
      id: 'different-layers-different-responsibilities',
      level: 2,
      text: 'One URL prefix, several different responsibilities'
    },
    {
      type: 'paragraph',
      text: 'Here is the part that causes most of the confusion: there is not necessarily one universal "prefix" setting. Different parts of your frontend stack may need to understand the application location for different reasons.'
    },
    {
      type: 'table',
      columns: ['Layer', 'Question it answers', 'Typical configuration'],
      rows: [
        ['Build tool', 'Where should generated public asset URLs point?', 'Vite `base`'],
        ['Client-side router', 'Where does the application route tree begin?', 'React Router `basename`'],
        ['Next.js framework', 'Under which URL sub-path should the application be deployed?', 'Next.js `basePath`'],
        ['Static asset/CDN layer', 'Where should certain static assets be fetched from?', 'Next.js `assetPrefix` in applicable setups'],
        ['Web server / hosting', 'How should incoming requests be routed to the application?', 'Server/CDN/reverse-proxy configuration']
      ]
    },
    {
      type: 'paragraph',
      text: 'These settings can appear to solve the same problem because they all contain some variation of "base" or "prefix". They do not necessarily control the same thing. Understanding this distinction prevents the classic debugging strategy of changing random slash-related configuration until the application stops screaming.'
    },
    {
      type: 'heading',
      id: 'vite-base',
      level: 2,
      text: 'Vite: the `base` option'
    },
    {
      type: 'paragraph',
      text: 'Vite calls its setting `base`. The default is `/`, meaning Vite assumes the application is publicly served from the root of the domain. Vite describes `base` as the base public path used when the application is served in development or production.'
    },
    {
      type: 'code',
      language: 'typescript',
      code: `// vite.config.ts

import { defineConfig } from 'vite'

export default defineConfig({
  base: '/admin/',
})`
    },
    {
      type: 'paragraph',
      text: 'If the application is deployed at `https://example.com/admin/`, this tells Vite that `/admin/` is the public base path. During the build, Vite adjusts asset URLs to respect that base. This includes JavaScript-imported assets, CSS `url()` references, and asset references in HTML.'
    },
    {
      type: 'code',
      language: 'markdown',
      code: `Without a custom base:

/assets/index-abc123.js

With base: '/admin/':

/admin/assets/index-abc123.js`
    },
    {
      type: 'paragraph',
      text: 'Vite also supports a full URL as the base, and it supports `./` or an empty string for certain embedded deployments. For the common case where your application lives at a known path on the same domain, an explicit pathname such as `/admin/` is the clearest configuration.'
    },
    {
      type: 'callout',
      variant: 'tip',
      title: 'Think "public URL", not "source directory"',
      text: 'Vite `base` has nothing to do with where your source files live on your computer. `base: "/admin/"` does not mean "look inside an admin folder in my project." It means "the built application is publicly served under `/admin/`."'
    },
    {
      type: 'heading',
      id: 'vite-base-url',
      level: 3,
      text: 'Reading the Vite base path in application code'
    },
    {
      type: 'paragraph',
      text: 'Vite exposes the configured public base path through `import.meta.env.BASE_URL`. This is useful when you need to construct a URL dynamically instead of referencing an asset in a form that Vite can statically process.'
    },
    {
      type: 'code',
      language: 'typescript',
      code: `const baseUrl = import.meta.env.BASE_URL

console.log(baseUrl)
// "/admin/"`
    },
    {
      type: 'paragraph',
      text: 'There is an important detail here: Vite statically replaces `import.meta.env.BASE_URL` during the build. Vite documents that it needs to appear exactly as `import.meta.env.BASE_URL`; dynamically accessing it as `import.meta.env["BASE_URL"]` is not equivalent.'
    },
    {
      type: 'heading',
      id: 'react-router-basename',
      level: 2,
      text: 'React Router: the `basename` option'
    },
    {
      type: 'paragraph',
      text: 'A Vite React application may also use a client-side router such as React Router. The router has a different question to answer: "What is the base of my route tree?" React Router calls this `basename`.'
    },
    {
      type: 'code',
      language: 'tsx',
      code: `import { BrowserRouter } from 'react-router-dom'

export default function App() {
  return (
    <BrowserRouter basename="/admin">
      {/* routes */}
    </BrowserRouter>
  )
}`
    },
    {
      type: 'paragraph',
      text: 'React Router documents `basename` as the base path for the application, and it is prepended to locations managed by the router. So if your application is mounted at `/admin`, a route such as `/settings` can correspond to the browser URL `/admin/settings`.'
    },
    {
      type: 'heading',
      id: 'vite-base-vs-router-basename',
      level: 3,
      text: 'Vite `base` and React Router `basename` are not the same thing'
    },
    {
      type: 'paragraph',
      text: 'This distinction is worth making very explicit. Vite is responsible for the build and the public URLs it generates. React Router is responsible for client-side navigation and matching URLs to your route tree. They may contain the same path because both need to understand where the application is mounted, but they operate at different layers.'
    },
    {
      type: 'code',
      language: 'markdown',
      code: `https://example.com/admin/settings
             │        │
             │        └── route: /settings
             │
             └── application base: /admin/


Vite:
  base: '/admin/'

React Router:
  basename: '/admin'`
    },
    {
      type: 'callout',
      variant: 'warning',
      title: 'Matching the two does not configure your server',
      text: 'Setting Vite `base` and React Router `basename` can make the generated asset URLs and client-side route URLs correct, but your production web server still has to know how to handle incoming requests. Configuration at the application layer does not automatically configure Nginx, Apache, CloudFront, S3, or another reverse proxy.'
    },
    {
      type: 'heading',
      id: 'nextjs-basepath',
      level: 2,
      text: 'Next.js: the `basePath` option'
    },
    {
      type: 'paragraph',
      text: 'Next.js uses a different name for the same broad deployment concept: `basePath`. Next.js documents `basePath` specifically as the configuration for deploying a Next.js application under a sub-path of a domain.'
    },
    {
      type: 'code',
      language: 'typescript',
      code: `// next.config.ts

import type { NextConfig } from 'next'

const nextConfig: NextConfig = {
  basePath: '/admin',
}

export default nextConfig`
    },
    {
      type: 'paragraph',
      text: 'With this configuration, the application is intended to be available under `https://example.com/admin/`. Unlike Vite, you do not configure a separate React Router basename for normal Next.js routing because Next.js owns the application routing system itself.'
    },
    {
      type: 'paragraph',
      text: 'Next.js also automatically applies the configured `basePath` when using `next/link` and the Next.js router. For example, a link written with `href="/about"` is rendered under `/admin/about` when `basePath` is `/admin`.'
    },
    {
      type: 'code',
      language: 'tsx',
      code: `import Link from 'next/link'

export default function HomePage() {
  return (
    <Link href="/about">
      About
    </Link>
  )
}

// With basePath: '/admin'
// The resulting URL is:
//
// /admin/about`
    },
    {
      type: 'callout',
      variant: 'note',
      title: 'Next.js handles more of the routing stack',
      text: 'This is one reason Vite + React Router and Next.js should not be configured as if they were the same architecture. With Vite, the build tool and router are separate pieces. Next.js is a framework that owns routing and rendering, so `basePath` integrates with its routing APIs.'
    },
    {
      type: 'heading',
      id: 'nextjs-basepath-build-time',
      level: 3,
      text: '`basePath` is a build-time setting'
    },
    {
      type: 'paragraph',
      text: 'Next.js documents that `basePath` must be configured at build time because the value is inlined into client-side bundles. If you change the value, you need to rebuild the application. This matters when designing deployment pipelines because the build needs to know which public path the application is being built for.'
    },
    {
      type: 'heading',
      id: 'nextjs-basepath-images',
      level: 3,
      text: 'Images need special attention'
    },
    {
      type: 'paragraph',
      text: 'Next.js automatically handles the base path for its links and router APIs, but you should not assume that every manually specified URL will be rewritten for you. The Next.js documentation specifically calls out `next/image`: when using an image from the public directory, the `basePath` needs to be included in the `src`.'
    },
    {
      type: 'code',
      language: 'tsx',
      code: `import Image from 'next/image'

export default function Profile() {
  return (
    <Image
      src="/admin/profile.png"
      alt="Profile"
      width={500}
      height={500}
    />
  )
}`
    },
    {
      type: 'heading',
      id: 'nextjs-basepath-vs-assetprefix',
      level: 2,
      text: 'Next.js `basePath` vs `assetPrefix`'
    },
    {
      type: 'paragraph',
      text: 'Next.js has another configuration option called `assetPrefix`, and this is where the terminology gets particularly dangerous. `basePath` answers "where is my application mounted?" `assetPrefix` is primarily about serving Next.js static assets from another location, such as a CDN.'
    },
    {
      type: 'code',
      language: 'typescript',
      code: `const nextConfig = {
  basePath: '/admin',
}

// Application:
// https://example.com/admin/


const nextConfig = {
  assetPrefix: 'https://cdn.example.com',
}

// Static Next.js assets can be loaded from:
// https://cdn.example.com/_next/...`
    },
    {
      type: 'paragraph',
      text: 'Next.js explicitly recommends `basePath` rather than a custom `assetPrefix` when the goal is to host the application on a sub-path such as `/docs`. `assetPrefix` is intended for CDN/static asset scenarios and does not cover every type of application URL.'
    },
    {
      type: 'callout',
      variant: 'warning',
      title: 'Do not use assetPrefix as a substitute for basePath',
      text: 'If your requirement is "this entire Next.js application should live at `/admin/`", use `basePath`. If the requirement is "serve Next.js static JavaScript and CSS from a CDN", `assetPrefix` may be appropriate. They solve different problems.'
    },
    {
      type: 'heading',
      id: 'server-routing',
      level: 2,
      text: 'The server still needs to understand the prefix'
    },
    {
      type: 'paragraph',
      text: 'A frontend configuration cannot completely solve a deployment problem by itself. Imagine a Vite React SPA deployed at `/admin/` with a client-side route `/admin/settings`. Clicking from `/admin/` to `/admin/settings` can work because React Router changes the browser URL without asking the server for a new HTML document. But if the user refreshes `/admin/settings`, the browser sends a real HTTP request for that URL.'
    },
    {
      type: 'code',
      language: 'markdown',
      code: `User clicks:

/admin/
    ↓
React Router
    ↓
/admin/settings


User refreshes:

Browser
    ↓
GET /admin/settings
    ↓
Production server`
    },
    {
      type: 'paragraph',
      text: 'If the production server has no rule telling it how to serve the application for `/admin/settings`, it can return a 404 before your React code ever runs. This is a different problem from generating the correct asset URLs. Your build configuration, router configuration, and hosting configuration all have different responsibilities.'
    },
    {
      type: 'callout',
      variant: 'note',
      title: 'This is why "it works when I click, but refresh gives 404" happens',
      text: 'Client-side navigation happens after the application has loaded. A hard refresh starts from the server. If the server does not know that `/admin/settings` belongs to your application, the request can fail before the frontend gets a chance to handle the route.'
    },
    {
      type: 'heading',
      id: 'complete-request-picture',
      level: 2,
      text: 'Putting all the pieces together'
    },
    {
      type: 'paragraph',
      text: 'Suppose a company hosts a React application at `https://company.com/admin/`. A request for `https://company.com/admin/settings` can involve several layers. The domain and web server determine where the request goes. The application build needs to generate assets relative to `/admin/`. The client-side router needs to understand `/admin` as the route base. Finally, the application renders the `settings` route.'
    },
    {
      type: 'steps',
      items: [
        {
          title: '1. Domain and hosting',
          text: 'The domain and reverse proxy/CDN decide where `/admin/*` requests are sent. This is infrastructure configuration, not a Vite or React configuration option.'
        },
        {
          title: '2. Build system',
          text: 'Vite uses `base: "/admin/"` to generate public asset URLs that point under the application prefix.'
        },
        {
          title: '3. Client-side router',
          text: 'React Router can use `basename: "/admin"` so that its route tree and navigation operate under the same prefix.'
        },
        {
          title: '4. Browser',
          text: 'The browser requests `/admin/assets/...` for application resources and `/admin/settings` when the user navigates to the settings page.'
        },
        {
          title: '5. Application',
          text: 'Once the application is running, the router interprets `/admin/settings` as the application route `/settings` and renders the appropriate page.'
        }
      ]
    },
    {
      type: 'heading',
      id: 'vite-nextjs-comparison',
      level: 2,
      text: 'Vite vs Next.js: the same problem, different architecture'
    },
    {
      type: 'table',
      columns: ['Concern', 'Vite + React', 'Next.js'],
      rows: [
        ['Application public base', '`base` in `vite.config.ts`', '`basePath` in `next.config.ts`'],
        ['Client-side routing', 'Usually configured separately, e.g. React Router `basename`', 'Handled by Next.js routing'],
        ['Read Vite base in code', '`import.meta.env.BASE_URL`', 'No equivalent Vite-style variable is needed for normal routing'],
        ['Static asset CDN', 'Depends on the Vite build/deployment setup', 'Next.js `assetPrefix` for applicable static asset/CDN setups'],
        [
          'Server request handling',
          'Configured by your production server/hosting',
          'Handled by the Next.js server or hosting architecture'
        ],
        [
          'Typical mental model',
          'Build tool + router + server are separate layers',
          'Framework integrates routing, rendering, and server behavior'
        ]
      ]
    },
    {
      type: 'heading',
      id: 'subdomain-vs-subpath',
      level: 2,
      text: 'A subdomain is not the same as a sub-path'
    },
    {
      type: 'paragraph',
      text: 'This distinction is easy to miss. These two URLs may look similar from a product perspective, but they represent different deployment arrangements.'
    },
    {
      type: 'code',
      language: 'markdown',
      code: `Subdomain:

https://admin.company.com/

Path-based deployment:

https://company.com/admin/`
    },
    {
      type: 'paragraph',
      text: 'With a subdomain, the application can still live at the root path `/` of that host. With a path-based deployment, the application lives under `/admin/`. Therefore, moving from `https://company.com/` to `https://admin.company.com/` does not automatically mean you need a Vite `base` or Next.js `basePath`. Moving from `https://company.com/` to `https://company.com/admin/` does.'
    },
    {
      type: 'heading',
      id: 'common-mistakes',
      level: 2,
      text: 'Common mistakes'
    },
    {
      type: 'list',
      style: 'unordered',
      items: [
        'Setting Vite `base` when the application is actually deployed at the root of its domain. A custom domain by itself does not require a base path.',
        'Setting Next.js `assetPrefix` when the actual requirement is to host the entire application under `/admin/`. Use `basePath` for that case.',
        'Configuring Vite `base` but forgetting that React Router may need its own `basename`.',
        'Assuming a correct base path automatically configures the production web server for client-side routes.',
        'Hardcoding `/admin/` throughout application code instead of using the framework/router configuration where appropriate.',
        'Assuming every manually constructed asset URL will automatically receive the configured prefix.',
        'Changing Next.js `basePath` at runtime and expecting an already-built client bundle to adapt. The value is part of the build.'
      ]
    },
    {
      type: 'heading',
      id: 'debugging-subpath-deployments',
      level: 2,
      text: 'How to debug a sub-path deployment'
    },
    {
      type: 'paragraph',
      text: 'When an application works on localhost but breaks after being deployed under a prefix, do not immediately start changing random configuration values. First identify which layer is actually failing.'
    },
    {
      type: 'steps',
      items: [
        {
          title: 'Check the actual public URL',
          text: 'Write down the exact URL where the application is supposed to live. Is it `https://example.com/` or `https://example.com/admin/`? This determines whether a base path is needed at all.'
        },
        {
          title: 'Check the browser Network tab',
          text: 'Look at failed JavaScript, CSS, font, and image requests. If the application is under `/admin/` but requests are going to `/assets/...`, your public asset base is probably wrong.'
        },
        {
          title: 'Check client-side navigation',
          text: 'Navigate from the application home page to a nested route. If navigation produces the wrong URL, inspect the router configuration.'
        },
        {
          title: 'Refresh a nested route',
          text: 'Open a route such as `/admin/settings` and refresh the browser. If it works through client-side navigation but fails on refresh, investigate your server, CDN, reverse proxy, or SPA fallback configuration.'
        },
        {
          title: 'Check manually constructed URLs',
          text: `Search the codebase for hardcoded paths beginning with '/' . These root-relative URLs bypass the application's base path unless the framework specifically processes them.`
        }
      ]
    },
    {
      type: 'heading',
      id: 'mental-model',
      level: 2,
      text: 'The mental model to remember'
    },
    {
      type: 'paragraph',
      text: 'You do not need to memorize every framework\'s configuration name. Start with the deployment question: "Where is this application mounted on the public web?" If the answer is `/`, there is usually no special path configuration. If the answer is `/admin/`, every relevant layer needs to understand that the application begins there.'
    },
    {
      type: 'code',
      language: 'markdown',
      code: `                     https://company.com/admin/
                                      │
                                      ▼
                              Application base
                                      │
                 ┌────────────────────┼────────────────────┐
                 │                    │                    │
                 ▼                    ▼                    ▼
              Vite                 Router              Next.js
               base              basename             basePath
                 │                    │                    │
                 ▼                    ▼                    ▼
            Asset URLs          Client routes       Framework routes


                         And underneath all of it:

                       Web server / CDN / hosting
                         "Where does /admin/* go?"`
    },
    {
      type: 'heading',
      id: 'final-takeaway',
      level: 2,
      text: 'Final takeaway'
    },
    {
      type: 'paragraph',
      text: 'A frontend base path is fundamentally a deployment concept. It answers one simple question: "Where does this application live inside the public URL space?" The framework-specific configuration exists because different tools control different parts of the application.'
    },
    {
      type: 'table',
      columns: ['Technology', 'Configuration', 'Primary responsibility'],
      rows: [
        ['Vite', '`base`', 'Tell Vite the public base path used when generating URLs'],
        ['Vite', '`import.meta.env.BASE_URL`', 'Read the configured Vite base path in application code'],
        ['React Router', '`basename`', "Tell the client-side router the application's route base"],
        ['Next.js', '`basePath`', 'Deploy the Next.js application under a domain sub-path'],
        ['Next.js', '`assetPrefix`', 'Serve applicable Next.js static assets from another location such as a CDN']
      ]
    },
    {
      type: 'paragraph',
      text: 'The important distinction is not `base` versus `basePath`. It is understanding the layers: the build system needs to generate the right URLs, the router needs to understand the right route space, and the server needs to send requests to the right application. Once those responsibilities are clear, deploying a frontend under `/admin/`, `/dashboard/`, `/docs/`, or `/my-project/` becomes a predictable configuration problem instead of a mysterious collection of slash-related errors.'
    }
  ]
};
