import type { Note } from '@/types/content';

// ─── MSW (Mock Service Worker) — network-level API mocking, the default over
// jest.mock()/ad-hoc fetch stubs in modern React/Next.js test suites. ───────────

export const mswNotes: Note[] = [
  {
    id: 'msw-why-msw',
    title: 'Why MSW over jest.mock() / fetch mocking?',
    summary:
      'MSW intercepts the actual network request instead of replacing the code that makes it — your components and API-client code run completely unmodified, in tests AND in the browser during development.',
    difficulty: 'basic',
    category: 'MSW',
    prerequisites: ['test-fund-mocking-strategies'],
    keyPoints: [
      "Module mocking (`jest.mock('./api')`) replaces your OWN code — the real fetch call, error handling, and response parsing never actually run, so bugs in that code go untested.",
      'MSW instead sits at the network layer: your component calls the real `fetch`/`axios`, and MSW intercepts the request before it leaves the process (Node) or before it hits the network (browser), returning a fake response.',
      'One consequence: switching your app from `fetch` to `axios`, or refactoring an internal API-client wrapper, requires ZERO changes to MSW-based tests — they only care about the URL/method being requested, not how the request is made.',
      "The same MSW handlers can run in actual local development (via a browser service worker) to build against a backend that doesn't exist yet, and in tests (via a Node interceptor) — one mock definition, two use cases.",
      'This is consistently framed as one of the most valuable modern additions to the React testing stack — it closes the biggest gap in the old "just jest.mock everything" approach.'
    ]
  },
  {
    id: 'msw-how-interception-works',
    title: 'How Request Interception Works',
    summary:
      'In the browser, MSW registers an actual Service Worker that intercepts fetch/XHR at the network level; in Node (tests), it patches the low-level request-making APIs directly — no service worker needed there.',
    difficulty: 'intermediate',
    category: 'MSW',
    prerequisites: ['msw-why-msw'],
    keyPoints: [
      "Browser mode: MSW installs a real Service Worker (`mockServiceWorker.js`, generated by `npx msw init`) that intercepts every `fetch`/`XMLHttpRequest` at the browser's network layer — indistinguishable from a real request as far as your app code is concerned.",
      "Node mode (used in Vitest/Jest): no service worker exists in Node, so MSW instead patches Node's low-level request-emitting internals (via its `@mswjs/interceptors` package) to catch outgoing requests before they hit the network.",
      "Because interception happens below the HTTP client library, MSW works identically whether your code uses `fetch`, `axios`, `ky`, or Next.js's extended `fetch` — none of them are aware anything is being intercepted.",
      "Unhandled requests (no matching handler) either pass through to the real network or trigger a warning/error depending on configuration (`onUnhandledRequest: 'error'` is the recommended strict setting for tests, catching typos in mocked URLs)."
    ]
  },
  {
    id: 'msw-setup-node',
    title: 'Setting Up MSW for Tests (Node)',
    summary:
      '`setupServer(...handlers)` from `msw/node`, started in a global `beforeAll` and reset between tests — the standard three-lifecycle-hook pattern.',
    difficulty: 'intermediate',
    category: 'MSW',
    prerequisites: ['msw-how-interception-works'],
    keyPoints: [
      '`setupServer(...handlers)` creates the interception server; `server.listen()` in `beforeAll`, `server.resetHandlers()` in `afterEach`, `server.close()` in `afterAll` is the standard lifecycle.',
      'Resetting handlers after every test (not just once) prevents a per-test override (`server.use(...)`) from leaking into unrelated tests — a common source of order-dependent flakiness when this step is skipped.',
      'Default/shared handlers typically live in a `handlers.ts` file imported by the setup; individual tests can layer a one-off override on top via `server.use(...)` for a specific error-case scenario.',
      "This setup goes in the same global test-setup file already used for RTL's `jest-dom` matchers (Vitest's `setupFiles` / Jest's `setupFilesAfterEach`)."
    ],
    codeSnippet: `// src/test/msw-server.ts
import { setupServer } from 'msw/node';
import { handlers } from './handlers';

export const server = setupServer(...handlers);

// src/test/setup.ts
import { server } from './msw-server';
beforeAll(() => server.listen({ onUnhandledRequest: 'error' }));
afterEach(() => server.resetHandlers());
afterAll(() => server.close());`
  },
  {
    id: 'msw-rest-handlers',
    title: 'Writing REST Handlers',
    summary:
      "`http.get(url, resolver)` (MSW v2's API) matches a method + URL pattern and returns a mocked `Response` — the core building block for every REST mock.",
    difficulty: 'intermediate',
    category: 'MSW',
    prerequisites: ['msw-setup-node'],
    keyPoints: [
      "MSW v2 uses the Fetch API's own `Request`/`Response` objects and a `http` import (`http.get`, `http.post`, ...) — earlier v1 used a different `rest` import with a different resolver signature; this distinction matters when reading older tutorials/answers.",
      "URL patterns support path parameters (`/users/:id`) accessible via the handler's `params` argument — `http.get('/users/:id', ({ params }) => HttpResponse.json({ id: params.id }))`.",
      'Reading the request body: `await request.json()` inside the resolver, since `request` is a real Fetch API `Request` object.',
      "Handlers can be scoped globally (shared defaults for the whole suite) or per-test via `server.use(...)` to override just one endpoint's response for a single scenario (e.g. simulating a validation error)."
    ],
    codeSnippet: `import { http, HttpResponse } from 'msw';

export const handlers = [
  http.get('/api/users/:id', ({ params }) => {
    return HttpResponse.json({ id: params.id, name: 'Ada Lovelace' });
  }),
  http.post('/api/users', async ({ request }) => {
    const body = await request.json();
    return HttpResponse.json({ id: 1, ...body }, { status: 201 });
  })
];`
  },
  {
    id: 'msw-error-simulation',
    title: 'Simulating Errors & Network Failures',
    summary:
      'Return a non-2xx `HttpResponse` for HTTP errors, or `HttpResponse.error()` to simulate a total network failure — both are one-line overrides in a specific test.',
    difficulty: 'intermediate',
    category: 'MSW',
    prerequisites: ['msw-rest-handlers'],
    keyPoints: [
      "HTTP error responses (400/401/404/500): `HttpResponse.json({ message: 'Invalid credentials' }, { status: 401 })` — tests the app's error-handling UI path.",
      'True network failure (DNS failure, connection refused, offline): `HttpResponse.error()` — this rejects the fetch promise entirely rather than resolving with an error status, exercising a different code path (`catch` blocks vs status-code branching).',
      "Delayed responses: MSW's `delay()` helper simulates slow networks to test loading states (`await delay(2000)` before returning) without an actual 2-second wait dragging down the real test suite runtime (MSW's delay can be sped up in test mode).",
      'One-off overrides via `server.use(...)` inside a specific test (reset automatically afterward by the `afterEach` hook) are the standard way to test a single failure scenario without touching the shared default handlers.'
    ],
    codeSnippet: `test('shows an error message on failed login', async () => {
  server.use(
    http.post('/api/login', () =>
      HttpResponse.json({ message: 'Invalid credentials' }, { status: 401 })
    )
  );
  render(<LoginForm />);
  // ... submit the form ...
  expect(await screen.findByText('Invalid credentials')).toBeInTheDocument();
});`
  },
  {
    id: 'msw-graphql-handlers',
    title: 'GraphQL Handlers',
    summary:
      'MSW mocks GraphQL the same way as REST — by intercepting HTTP — but matches on the OPERATION NAME inside the request body instead of the URL.',
    difficulty: 'intermediate',
    category: 'MSW',
    prerequisites: ['msw-rest-handlers'],
    keyPoints: [
      "GraphQL requests are just POST requests to a single endpoint with a query/mutation in the body — MSW's `graphql` handler helper parses that body and matches by operation name rather than URL path.",
      "`graphql.query('GetUser', ({ variables }) => HttpResponse.json({ data: { user: { id: variables.id, name: 'Ada' } } }))` — the operation name must match exactly what the client sends.",
      "This means the mock doesn't care which URL the GraphQL client posts to (useful since some apps proxy or rewrite the GraphQL endpoint) — only the operation name and variables matter.",
      'Same error-simulation and per-test override patterns from REST handlers apply identically here (`errors` field in the response for GraphQL-level errors, or a non-200 status for transport-level failures).'
    ]
  },
  {
    id: 'msw-testing-route-handlers-with-msw',
    title: 'Testing Route Handlers That Call External APIs',
    summary:
      "When a Next.js Route Handler itself calls out to another API (a third-party service, a microservice), MSW mocks THAT outgoing call so the handler's logic can be tested without a real dependency.",
    difficulty: 'intermediate',
    category: 'MSW',
    prerequisites: ['msw-rest-handlers', 'vitest-testing-route-handlers'],
    keyPoints: [
      'A Route Handler that proxies or aggregates data from an external API is effectively a small backend — testing it means mocking ITS outgoing requests, not the incoming request to the handler itself.',
      "Since MSW's Node interceptor works below any HTTP client, it mocks the Route Handler's outgoing `fetch` calls the same way it would mock a browser component's — no special Next.js-specific MSW configuration needed.",
      'This lets a test exercise the Route Handler\'s real aggregation/transformation/error-handling logic while controlling exactly what the "external API" returns, including edge cases (rate limits, malformed data) that would be hard to trigger against the real service.',
      "Distinct from mocking the DATABASE layer (typically done via a real test database, an in-memory one, or an ORM-level mock) — MSW's job here is specifically the HTTP boundary."
    ]
  }
];
